apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: nginx
    meta.helm.sh/release-namespace: nginx-app
  name: nginx-prometheus-port
  namespace: nginx-app
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 9113
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx
  policyTypes:
  - Ingress
  - Egress
